// <auto-generated />
using System;
using AsistanNobetYonetimi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AsistanNobetYonetimi.Migrations
{
    [DbContext(typeof(NobetDbContext))]
    [Migration("20241212235646_AddIsAvailableToRandevu")]
    partial class AddIsAvailableToRandevu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AsistanNobetYonetimi.Models.AcilDurum", b =>
                {
                    b.Property<int>("AcilDurumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcilDurumID"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GondermeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("AcilDurumID");

                    b.ToTable("acildurumlar");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"), 1L, 1);

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Asistan", b =>
                {
                    b.Property<int>("AsistanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistanID"), 1L, 1);

                    b.Property<string>("AsistanIsimSoyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsistanUnvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TakvimID")
                        .HasColumnType("int");

                    b.HasKey("AsistanID");

                    b.HasIndex("BolumID");

                    b.HasIndex("TakvimID");

                    b.ToTable("asistanlar");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Bolum", b =>
                {
                    b.Property<int>("BolumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumID"), 1L, 1);

                    b.Property<int>("HastaSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BolumID");

                    b.ToTable("bolumler");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Nobet", b =>
                {
                    b.Property<int>("NobetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NobetID"), 1L, 1);

                    b.Property<int>("AsistanID")
                        .HasColumnType("int");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("NobetSaati")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NobetTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TakvimID")
                        .HasColumnType("int");

                    b.HasKey("NobetID");

                    b.HasIndex("AsistanID");

                    b.HasIndex("BolumID");

                    b.HasIndex("TakvimID");

                    b.ToTable("nobetler");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.OgretimUyesi", b =>
                {
                    b.Property<int>("OgretimUyesiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgretimUyesiID"), 1L, 1);

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsimSoyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TakvimID")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgretimUyesiID");

                    b.HasIndex("BolumID");

                    b.HasIndex("TakvimID");

                    b.ToTable("ogretimuyeleri");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Randevu", b =>
                {
                    b.Property<int>("RandevuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuID"), 1L, 1);

                    b.Property<int>("AsistanID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("OgretimUyesiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TakvimID")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RandevuID");

                    b.HasIndex("AsistanID");

                    b.HasIndex("OgretimUyesiID");

                    b.HasIndex("TakvimID");

                    b.ToTable("randevular");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Takvim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.HasKey("ID");

                    b.ToTable("takvim");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Asistan", b =>
                {
                    b.HasOne("AsistanNobetYonetimi.Models.Bolum", "bolum")
                        .WithMany("asistan")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AsistanNobetYonetimi.Models.Takvim", null)
                        .WithMany("asistan")
                        .HasForeignKey("TakvimID");

                    b.Navigation("bolum");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Nobet", b =>
                {
                    b.HasOne("AsistanNobetYonetimi.Models.Asistan", "asistan")
                        .WithMany("nobet")
                        .HasForeignKey("AsistanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsistanNobetYonetimi.Models.Bolum", "bolum")
                        .WithMany("nobet")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AsistanNobetYonetimi.Models.Takvim", null)
                        .WithMany("nobet")
                        .HasForeignKey("TakvimID");

                    b.Navigation("asistan");

                    b.Navigation("bolum");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.OgretimUyesi", b =>
                {
                    b.HasOne("AsistanNobetYonetimi.Models.Bolum", "bolum")
                        .WithMany("ogretimuyesi")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsistanNobetYonetimi.Models.Takvim", null)
                        .WithMany("ogretimuyesi")
                        .HasForeignKey("TakvimID");

                    b.Navigation("bolum");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Randevu", b =>
                {
                    b.HasOne("AsistanNobetYonetimi.Models.Asistan", "asistan")
                        .WithMany("randevu")
                        .HasForeignKey("AsistanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsistanNobetYonetimi.Models.OgretimUyesi", "ogretimUyesi")
                        .WithMany("randevu")
                        .HasForeignKey("OgretimUyesiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsistanNobetYonetimi.Models.Takvim", null)
                        .WithMany("randevu")
                        .HasForeignKey("TakvimID");

                    b.Navigation("asistan");

                    b.Navigation("ogretimUyesi");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Asistan", b =>
                {
                    b.Navigation("nobet");

                    b.Navigation("randevu");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Bolum", b =>
                {
                    b.Navigation("asistan");

                    b.Navigation("nobet");

                    b.Navigation("ogretimuyesi");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.OgretimUyesi", b =>
                {
                    b.Navigation("randevu");
                });

            modelBuilder.Entity("AsistanNobetYonetimi.Models.Takvim", b =>
                {
                    b.Navigation("asistan");

                    b.Navigation("nobet");

                    b.Navigation("ogretimuyesi");

                    b.Navigation("randevu");
                });
#pragma warning restore 612, 618
        }
    }
}
